"""Create content_versions, content_comments, content_activities tables

Revision ID: 8682bf620820
Revises: 0ee208322662
Create Date: 2026-09-29 21:07:07.294911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8682bf620820'
down_revision: Union[str, Sequence[str], None] = '0ee208322662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_activities_content_id'), 'content_activities', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_activities_id'), 'content_activities', ['id'], unique=False)
    op.create_table('content_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_comments_content_id'), 'content_comments', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_comments_id'), 'content_comments', ['id'], unique=False)
    op.create_table('content_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('content_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_versions_content_id'), 'content_versions', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_versions_id'), 'content_versions', ['id'], unique=False)
    op.create_index(op.f('ix_content_versions_version_number'), 'content_versions', ['version_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_versions_version_number'), table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_id'), table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_content_id'), table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_index(op.f('ix_content_comments_id'), table_name='content_comments')
    op.drop_index(op.f('ix_content_comments_content_id'), table_name='content_comments')
    op.drop_table('content_comments')
    op.drop_index(op.f('ix_content_activities_id'), table_name='content_activities')
    op.drop_index(op.f('ix_content_activities_content_id'), table_name='content_activities')
    op.drop_table('content_activities')
    # ### end Alembic commands ###
